### ISSUE TITLE
Changed meaning of ./= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [rened/ExtremelyRandomizedTrees.jl#1]
Your code uses `x ./= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x ./ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `./` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

It wasn't completely clear to me if your code is okay, because I couldn't tell at first glance whether `b.pxy[i,1]` is a mutable array (ok) or a number (not ok) in `b.pxy[i,1] ./= length(x)`.  But if it is a problem you could always change it to `x = x ./ y`.

**Comment by rened** [comment]
Thank you very much for this detailed input! I am just going through my packages to make them fit for 0.5 ;-)

This instance of `./`is fine, we can leave it as is.
